### ISSUE TITLE
Feature Request: deflate HTTP parameter

### ISSUE THREAD

**Issue by heaviss** [owasp-modsecurity/ModSecurity#1584]
Hi! I need to deal with http parameter which have been zipped (deflate algorithm) and then base64-encoded. 
Is it possible to implement transformation function to deflate (t:unzipDeflate) ?
What I need to do it?
I have almost no experience in developing in C, but I'll try to do as much as I can.

**Comment by victorhora** [comment]
Hi @heaviss 

Have you tried forcing decompression using [mod_deflate](https://httpd.apache.org/docs/current/mod/mod_deflate.htm) or [ngx_http_gunzip_module](https://nginx.org/en/docs/http/ngx_http_gunzip_module.html)?

**Comment by heaviss** [comment]
Hi @victorhora 
From [mod_deflate](https://httpd.apache.org/docs/current/mod/mod_deflate.html):
> The deflate encoding is not supported

Also, as I understand, mod_deflate can't decode one specific parameter, only full request/response.

I tried to do this with lua script, but it was unstable.
I need this to work with 3D-Secure service. There is a POST request with "content type: application/x-www-form-urlencoded", and parameter PaReq in the body. PaReq is an XML document, compressed using the DEFLATE algorithm, and then Base64-encoded and URL-encoded. 
I think this feature will be great for PCI DSS compliance.

**Comment by zimmerle** [comment]
@azurit proposed a Lua script in #2494. The idea is to have a transformation to perform **gunzip**.

**Comment by marcstern** [comment]
Custom transformations can be developed. This is definetely one
